version: 2
jobs:
  tests:
    docker:
       - image: circleci/ruby:2.4.2

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "Gemfile" }}

      - run:
          name: run tests
          command: bundle exec rake

      - run:
          name: build gem
          command: bundle exec rake build

      - store_test_results:
          path: ~/repo/test-results
      - store_artifacts:
          path: ~/repo/test-results
          destination: test-results
      - store_artifacts:
          path: ~/repo/pkg
          destination: pkg

  release:
    docker:
      - image: circleci/ruby:2.4.2
    steps:
      - checkout
      - run: gem build fastlane-plugin-coveralls.gemspec
      - run: .circleci/check-tag.sh
      - run: .circleci/export-api-key.sh
      - run: gem push fastlane-plugin-coveralls*.gem
      - store_artifacts:
          path: fastlane-plugin-coveralls*.gem

workflows:
  version: 2
  tests:
    jobs:
      - tests
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
